SHELL=/bin/sh

TOP_SRCDIR= ..
SRCDIR    = .
INCLUDES  = -I${TOP_SRCDIR}/include
MAKEDEPEND= mkdep
RM	  = rm -f
CFLAGS	  = ${INCLUDES} -Wall ${EXTRA}

ifeq ($(OSTYPE),darwin)

CFLAGS  = ${INCLUDES} -Wall ${EXTRA} -arch i386

endif

MODULE    = database
PROG	  = mumps

SRCS = 	db_buffer.c \
	db_daemon.c \
	db_get.c \
	db_ic.c \
	db_kill.c \
	db_locate.c \
	db_main.c \
	db_rekey.c \
	db_set.c \
	db_uci.c \
	db_util.c \
	db_view.c

OBJS = 	db_buffer.o \
	db_daemon.o \
	db_get.o \
	db_ic.o \
	db_kill.o \
	db_locate.o \
	db_main.o \
	db_rekey.o \
	db_set.o \
	db_uci.o \
	db_util.o \
	db_view.o

all:	${OBJS}

depend:
	${MAKEDEPEND} ${INCLUDES} ${SRCS}

clean:
	${RM} ${OBJS} Makefile.bak .depend


# DO NOT DELETE

db_buffer.o: /usr/include/stdio.h /usr/include/features.h
db_buffer.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_buffer.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_buffer.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_buffer.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_buffer.o: /usr/include/libio.h /usr/include/_G_config.h
db_buffer.o: /usr/include/wchar.h /usr/include/stdarg.h
db_buffer.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
db_buffer.o: /usr/include/stdlib.h /usr/include/sys/types.h
db_buffer.o: /usr/include/time.h /usr/include/endian.h
db_buffer.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_buffer.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_buffer.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_buffer.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_buffer.o: /usr/include/alloca.h /usr/include/string.h
db_buffer.o: /usr/include/xlocale.h /usr/include/strings.h
db_buffer.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
db_buffer.o: /usr/include/bits/confname.h /usr/include/getopt.h
db_buffer.o: /usr/include/ctype.h /usr/include/sys/ipc.h
db_buffer.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_buffer.o: /usr/include/sys/sem.h /usr/include/bits/sem.h
db_buffer.o: ../include/mumps.h ../include/database.h ../include/proto.h
db_buffer.o: ../include/error.h
db_daemon.o: /usr/include/stdio.h /usr/include/features.h
db_daemon.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_daemon.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_daemon.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_daemon.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_daemon.o: /usr/include/libio.h /usr/include/_G_config.h
db_daemon.o: /usr/include/wchar.h /usr/include/stdarg.h
db_daemon.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
db_daemon.o: /usr/include/stdlib.h /usr/include/sys/types.h
db_daemon.o: /usr/include/time.h /usr/include/endian.h
db_daemon.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_daemon.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_daemon.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_daemon.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_daemon.o: /usr/include/alloca.h /usr/include/string.h
db_daemon.o: /usr/include/xlocale.h /usr/include/strings.h
db_daemon.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
db_daemon.o: /usr/include/bits/confname.h /usr/include/getopt.h
db_daemon.o: /usr/include/ctype.h /usr/include/errno.h
db_daemon.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
db_daemon.o: /usr/include/asm/errno.h /usr/include/asm-generic/errno.h
db_daemon.o: /usr/include/asm-generic/errno-base.h /usr/include/fcntl.h
db_daemon.o: /usr/include/bits/fcntl.h /usr/include/signal.h
db_daemon.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
db_daemon.o: /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h
db_daemon.o: /usr/include/bits/sigstack.h /usr/include/bits/sigthread.h
db_daemon.o: /usr/include/sys/shm.h /usr/include/sys/ipc.h
db_daemon.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_daemon.o: /usr/include/bits/shm.h /usr/include/sys/sem.h
db_daemon.o: /usr/include/bits/sem.h ../include/mumps.h ../include/database.h
db_daemon.o: ../include/proto.h ../include/error.h
db_get.o: /usr/include/stdio.h /usr/include/features.h
db_get.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_get.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_get.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_get.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_get.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_get.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_get.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_get.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_get.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_get.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_get.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_get.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_get.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_get.o: /usr/include/strings.h /usr/include/unistd.h
db_get.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_get.o: /usr/include/getopt.h /usr/include/ctype.h /usr/include/sys/ipc.h
db_get.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_get.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_get.o: ../include/database.h ../include/proto.h ../include/error.h
db_ic.o: /usr/include/stdio.h /usr/include/features.h
db_ic.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_ic.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_ic.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_ic.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_ic.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_ic.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_ic.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_ic.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_ic.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_ic.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_ic.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_ic.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_ic.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_ic.o: /usr/include/strings.h /usr/include/unistd.h
db_ic.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_ic.o: /usr/include/getopt.h /usr/include/ctype.h /usr/include/sys/ipc.h
db_ic.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_ic.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_ic.o: ../include/database.h ../include/proto.h ../include/error.h
db_kill.o: /usr/include/stdio.h /usr/include/features.h
db_kill.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_kill.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_kill.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_kill.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_kill.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_kill.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_kill.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_kill.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_kill.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_kill.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_kill.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_kill.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_kill.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_kill.o: /usr/include/strings.h /usr/include/unistd.h
db_kill.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_kill.o: /usr/include/getopt.h /usr/include/ctype.h ../include/mumps.h
db_kill.o: ../include/database.h ../include/proto.h ../include/error.h
db_locate.o: /usr/include/stdio.h /usr/include/features.h
db_locate.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_locate.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_locate.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_locate.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_locate.o: /usr/include/libio.h /usr/include/_G_config.h
db_locate.o: /usr/include/wchar.h /usr/include/stdarg.h
db_locate.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
db_locate.o: /usr/include/stdlib.h /usr/include/sys/types.h
db_locate.o: /usr/include/time.h /usr/include/endian.h
db_locate.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_locate.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_locate.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_locate.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_locate.o: /usr/include/alloca.h /usr/include/string.h
db_locate.o: /usr/include/xlocale.h /usr/include/strings.h
db_locate.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
db_locate.o: /usr/include/bits/confname.h /usr/include/getopt.h
db_locate.o: /usr/include/ctype.h /usr/include/sys/ipc.h
db_locate.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_locate.o: /usr/include/sys/sem.h /usr/include/bits/sem.h
db_locate.o: ../include/mumps.h ../include/database.h ../include/proto.h
db_locate.o: ../include/error.h
db_main.o: /usr/include/stdio.h /usr/include/features.h
db_main.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_main.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_main.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_main.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_main.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_main.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_main.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_main.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_main.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_main.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_main.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_main.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_main.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_main.o: /usr/include/strings.h /usr/include/unistd.h
db_main.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_main.o: /usr/include/getopt.h /usr/include/fcntl.h
db_main.o: /usr/include/bits/fcntl.h /usr/include/ctype.h
db_main.o: /usr/include/errno.h /usr/include/bits/errno.h
db_main.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
db_main.o: /usr/include/asm-generic/errno.h
db_main.o: /usr/include/asm-generic/errno-base.h /usr/include/sys/ipc.h
db_main.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_main.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_main.o: ../include/database.h ../include/proto.h ../include/error.h
db_rekey.o: /usr/include/stdio.h /usr/include/features.h
db_rekey.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_rekey.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_rekey.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_rekey.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_rekey.o: /usr/include/libio.h /usr/include/_G_config.h
db_rekey.o: /usr/include/wchar.h /usr/include/stdarg.h
db_rekey.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
db_rekey.o: /usr/include/stdlib.h /usr/include/sys/types.h
db_rekey.o: /usr/include/time.h /usr/include/endian.h
db_rekey.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_rekey.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_rekey.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_rekey.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_rekey.o: /usr/include/alloca.h /usr/include/string.h
db_rekey.o: /usr/include/xlocale.h /usr/include/strings.h
db_rekey.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
db_rekey.o: /usr/include/bits/confname.h /usr/include/getopt.h
db_rekey.o: /usr/include/ctype.h /usr/include/sys/ipc.h
db_rekey.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_rekey.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_rekey.o: ../include/database.h ../include/proto.h ../include/error.h
db_set.o: /usr/include/stdio.h /usr/include/features.h
db_set.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_set.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_set.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_set.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_set.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_set.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_set.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_set.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_set.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_set.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_set.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_set.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_set.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_set.o: /usr/include/strings.h /usr/include/unistd.h
db_set.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_set.o: /usr/include/getopt.h /usr/include/ctype.h /usr/include/sys/ipc.h
db_set.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_set.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_set.o: ../include/database.h ../include/proto.h ../include/error.h
db_uci.o: /usr/include/stdio.h /usr/include/features.h
db_uci.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_uci.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_uci.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_uci.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_uci.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_uci.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_uci.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_uci.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_uci.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_uci.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_uci.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_uci.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_uci.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_uci.o: /usr/include/strings.h /usr/include/unistd.h
db_uci.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_uci.o: /usr/include/getopt.h /usr/include/ctype.h /usr/include/sys/ipc.h
db_uci.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_uci.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_uci.o: ../include/database.h ../include/proto.h ../include/error.h
db_util.o: /usr/include/stdio.h /usr/include/features.h
db_util.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_util.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_util.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_util.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_util.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_util.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_util.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_util.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_util.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_util.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_util.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_util.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_util.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_util.o: /usr/include/strings.h /usr/include/unistd.h
db_util.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_util.o: /usr/include/getopt.h /usr/include/fcntl.h
db_util.o: /usr/include/bits/fcntl.h /usr/include/ctype.h
db_util.o: /usr/include/sys/ipc.h /usr/include/bits/ipctypes.h
db_util.o: /usr/include/bits/ipc.h /usr/include/sys/sem.h
db_util.o: /usr/include/bits/sem.h /usr/include/sys/stat.h
db_util.o: /usr/include/bits/stat.h ../include/mumps.h ../include/database.h
db_util.o: ../include/proto.h ../include/error.h
db_view.o: /usr/include/stdio.h /usr/include/features.h
db_view.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
db_view.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
db_view.o: /usr/include/gnu/stubs-32.h /usr/include/stddef.h
db_view.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
db_view.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
db_view.o: /usr/include/stdarg.h /usr/include/bits/stdio_lim.h
db_view.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
db_view.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
db_view.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
db_view.o: /usr/include/sys/select.h /usr/include/bits/select.h
db_view.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
db_view.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
db_view.o: /usr/include/alloca.h /usr/include/string.h /usr/include/xlocale.h
db_view.o: /usr/include/strings.h /usr/include/unistd.h
db_view.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
db_view.o: /usr/include/getopt.h /usr/include/ctype.h /usr/include/sys/ipc.h
db_view.o: /usr/include/bits/ipctypes.h /usr/include/bits/ipc.h
db_view.o: /usr/include/sys/sem.h /usr/include/bits/sem.h ../include/mumps.h
db_view.o: ../include/database.h ../include/proto.h ../include/error.h
